import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import chalk from 'chalk';
import ora from 'ora';
import type { Command } from 'commander';
import type { TechStack } from '../types.js';
import { loadConfig, requireSwarmDir, autoDetectStack, autoInit } from '../core/config.js';
import { extractConventions, buildConventionPrompt } from '../core/convention-extractor.js';

export function registerLearn(program: Command): void {
  program
    .command('learn')
    .description('Scan codebase and extract project conventions for all agents to follow')
    .option('-s, --stack <stack>', 'Tech stack override')
    .option('--refresh', 'Re-scan even if conventions file exists')
    .option('--merge', 'Update existing conventions without overwriting manual edits')
    .option('--show', 'Print conventions to stdout without saving')
    .action(async (opts) => {
      let swarmDir: string;
      try {
        swarmDir = requireSwarmDir();
      } catch {
        const cwd = process.cwd();
        const stack = (opts.stack as TechStack) || autoDetectStack(cwd);
        const projectName = cwd.split('/').pop() || 'my-project';
        console.log(chalk.yellow(`No .swarm/ found — auto-initializing (stack: ${stack})...`));
        swarmDir = autoInit(projectName, stack, cwd);
      }

      const config = loadConfig();
      const cwd = process.cwd();
      const conventionsPath = join(swarmDir, 'conventions.md');

      // Check for existing conventions
      if (existsSync(conventionsPath) && !opts.refresh && !opts.merge && !opts.show) {
        console.log(chalk.yellow(`Conventions already exist at ${conventionsPath}`));
        console.log(chalk.dim('Use --refresh to re-scan, --merge to update, or --show to view'));
        console.log('');
        const existing = readFileSync(conventionsPath, 'utf-8');
        console.log(existing);
        return;
      }

      const spinner = ora('Scanning codebase for conventions...').start();

      try {
        const conventions = extractConventions(cwd);

        if (!conventions.trim()) {
          spinner.warn('No conventions detected. Your project may be too small or use unfamiliar patterns.');
          return;
        }

        const conventionDoc = buildConventionPrompt(conventions);

        if (opts.show) {
          spinner.stop();
          console.log(conventionDoc);
          return;
        }

        if (opts.merge && existsSync(conventionsPath)) {
          // Merge: append new conventions after a separator, preserving manual edits
          const existing = readFileSync(conventionsPath, 'utf-8');
          const merged = [
            existing.trimEnd(),
            '',
            '---',
            '',
            '<!-- Auto-updated by swarm learn --merge -->',
            conventions,
          ].join('\n');
          writeFileSync(conventionsPath, merged, 'utf-8');
          spinner.succeed(`Conventions merged into ${conventionsPath}`);
        } else {
          // Full write
          const header = [
            '# Project Conventions',
            '',
            `<!-- Generated by \`hivemind learn\` on ${new Date().toISOString().split('T')[0]} -->`,
            '<!-- Edit freely — manual changes are preserved with --merge -->',
            '',
          ].join('\n');
          writeFileSync(conventionsPath, header + conventions + '\n', 'utf-8');
          spinner.succeed(`Conventions saved to ${conventionsPath}`);
        }

        console.log('');
        console.log(chalk.dim('Conventions will be injected into all pipeline agents automatically.'));
        console.log(chalk.dim('Edit .swarm/conventions.md to customize. Re-run with --refresh to re-scan.'));
      } catch (err) {
        spinner.fail(`Failed to extract conventions: ${err instanceof Error ? err.message : String(err)}`);
        process.exit(1);
      }
    });
}

/**
 * Load conventions from .swarm/conventions.md if it exists.
 * Returns the convention text ready for injection into agent system prompts,
 * or empty string if no conventions file.
 */
export function loadConventions(swarmDir: string): string {
  const conventionsPath = join(swarmDir, 'conventions.md');
  if (!existsSync(conventionsPath)) return '';
  try {
    const raw = readFileSync(conventionsPath, 'utf-8');
    if (!raw.trim()) return '';
    return buildConventionPrompt(raw);
  } catch {
    return '';
  }
}
