import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { createInterface } from 'node:readline';
import chalk from 'chalk';
import type { Command } from 'commander';
import { analyzeAmbiguity, generateScopeDocument } from '../core/ambiguity-detector.js';
import type { ScopeOption, AmbiguityAnalysis, ScopeDocument } from '../core/ambiguity-detector.js';

function vaguenessColor(score: number): (text: string) => string {
  if (score < 30) return chalk.green;
  if (score <= 60) return chalk.yellow;
  return chalk.red;
}

function riskColor(risk: string): (text: string) => string {
  if (risk === 'low') return chalk.green;
  if (risk === 'medium') return chalk.yellow;
  return chalk.red;
}

function classificationBadge(classification: string): string {
  const badges: Record<string, string> = {
    'clear-small': chalk.bgGreen.black(' CLEAR-SMALL '),
    'clear-large': chalk.bgBlue.white(' CLEAR-LARGE '),
    'ambiguous': chalk.bgYellow.black(' AMBIGUOUS '),
    'risky': chalk.bgRed.white(' RISKY '),
  };
  return badges[classification] || classification;
}

function printAnalysis(analysis: AmbiguityAnalysis, request: string): void {
  console.log();
  console.log(chalk.bold('Scope Analysis'));
  console.log(chalk.dim('─'.repeat(60)));
  console.log();

  // Request
  console.log(chalk.dim('Request: ') + request);
  console.log();

  // Vagueness & classification
  const colorFn = vaguenessColor(analysis.vaguenessScore);
  const bar = '█'.repeat(Math.round(analysis.vaguenessScore / 5)) + '░'.repeat(20 - Math.round(analysis.vaguenessScore / 5));
  console.log(`  Vagueness:      ${colorFn(`${analysis.vaguenessScore}/100`)} ${chalk.dim(bar)}`);
  console.log(`  Classification: ${classificationBadge(analysis.classification)}`);
  console.log(`  Scope size:     ${chalk.white(analysis.scopeSize)}`);
  console.log(`  Est. cost:      ${chalk.white('$' + analysis.estimatedCost.toFixed(2))}`);
  console.log(`  Est. files:     ${chalk.white(String(analysis.estimatedFiles))}`);
  console.log();

  // Risk factors
  if (analysis.riskFactors.length > 0) {
    console.log(chalk.red.bold('  ⚠ Risk Factors'));
    for (const factor of analysis.riskFactors) {
      console.log(chalk.red(`    • ${factor}`));
    }
    console.log();
  }

  // Missing context
  if (analysis.missingContext.length > 0) {
    console.log(chalk.yellow.bold('  ? Missing Context'));
    for (const item of analysis.missingContext) {
      console.log(chalk.yellow(`    • ${item}`));
    }
    console.log();
  }

  // Questions
  if (analysis.questions.length > 0) {
    console.log(chalk.cyan.bold('  Clarifying Questions'));
    for (let i = 0; i < analysis.questions.length; i++) {
      console.log(chalk.cyan(`    ${i + 1}. ${analysis.questions[i]}`));
    }
    console.log();
  }

  // Options
  console.log(chalk.bold('  Options'));
  console.log(chalk.dim('  ' + '─'.repeat(56)));
  for (let i = 0; i < analysis.options.length; i++) {
    const opt = analysis.options[i]!;
    const rec = opt.recommended ? chalk.green(' ★ RECOMMENDED') : '';
    const rFn = riskColor(opt.risk);
    console.log();
    console.log(`  ${chalk.bold(`[${i + 1}]`)} ${chalk.bold.white(opt.name)}${rec}`);
    console.log(`      ${chalk.dim(opt.description)}`);
    console.log(`      Cost: ${chalk.white('$' + opt.estimatedCost.toFixed(2))}  Time: ${chalk.white(opt.estimatedTime)}  Risk: ${rFn(opt.risk)}`);
    console.log(`      Tradeoffs:`);
    for (const t of opt.tradeoffs) {
      console.log(`        ${chalk.dim('•')} ${chalk.dim(t)}`);
    }
  }
  console.log();
}

function formatScopeMarkdown(request: string, doc: ScopeDocument, analysis: AmbiguityAnalysis): string {
  const lines: string[] = [];
  lines.push('# SCOPE.md');
  lines.push('');
  lines.push(`> Generated by \`hivemind scope\` on ${new Date().toISOString().slice(0, 10)}`);
  lines.push('');
  lines.push('## Request');
  lines.push('');
  lines.push(request);
  lines.push('');
  lines.push('## Approach');
  lines.push('');
  lines.push(doc.approach);
  lines.push('');
  lines.push('## Will Build');
  lines.push('');
  for (const item of doc.willBuild) {
    lines.push(`- ${item}`);
  }
  lines.push('');
  lines.push('## Will NOT Build');
  lines.push('');
  for (const item of doc.willNotBuild) {
    lines.push(`- ${item}`);
  }
  lines.push('');
  lines.push('## Assumptions');
  lines.push('');
  for (const item of doc.assumptions) {
    lines.push(`- ${item}`);
  }
  lines.push('');
  lines.push('## Estimates');
  lines.push('');
  lines.push(`- **Cost:** $${doc.estimatedCost.toFixed(2)}`);
  lines.push(`- **Scope size:** ${analysis.scopeSize}`);
  lines.push(`- **Estimated files affected:** ${analysis.estimatedFiles}`);
  lines.push('');
  lines.push('## Risk');
  lines.push('');
  lines.push(doc.risk);
  if (analysis.riskFactors.length > 0) {
    lines.push('');
    lines.push('### Risk Factors');
    lines.push('');
    for (const factor of analysis.riskFactors) {
      lines.push(`- ${factor}`);
    }
  }
  lines.push('');

  return lines.join('\n');
}

function promptForOption(optionCount: number): Promise<number> {
  return new Promise((resolve) => {
    const rl = createInterface({ input: process.stdin, output: process.stdout });
    rl.question(chalk.bold(`Select an option [1-${optionCount}] or 'q' to quit: `), (answer) => {
      rl.close();
      const trimmed = answer.trim().toLowerCase();
      if (trimmed === 'q' || trimmed === 'quit') {
        resolve(-1);
        return;
      }
      const num = parseInt(trimmed, 10);
      if (isNaN(num) || num < 1 || num > optionCount) {
        resolve(-1);
        return;
      }
      resolve(num - 1); // zero-indexed
    });
  });
}

export function registerScope(program: Command): void {
  program
    .command('scope')
    .description('Analyze and negotiate requirements before running the pipeline')
    .argument('<request>', 'Feature request or task description to scope')
    .option('-o, --output <path>', 'Output path for SCOPE.md', 'SCOPE.md')
    .option('--no-interactive', 'Skip interactive option selection (just show analysis)')
    .action(async (request: string, opts) => {
      const cwd = process.cwd();

      console.log(chalk.dim('Analyzing request scope...'));
      const analysis = analyzeAmbiguity(request, cwd);

      printAnalysis(analysis, request);

      if (opts.interactive === false) {
        return;
      }

      const choice = await promptForOption(analysis.options.length);
      if (choice === -1) {
        console.log(chalk.dim('Cancelled.'));
        return;
      }

      const chosenOption = analysis.options[choice]!;
      console.log();
      console.log(chalk.green(`Selected: ${chalk.bold(chosenOption.name)}`));

      const doc = generateScopeDocument(request, chosenOption, analysis);
      const markdown = formatScopeMarkdown(request, doc, analysis);

      const outputPath = join(cwd, opts.output);
      writeFileSync(outputPath, markdown, 'utf-8');
      console.log(chalk.green(`Scope document saved to ${chalk.bold(outputPath)}`));
      console.log();
      console.log(chalk.dim('Run the pipeline with:'));
      console.log(chalk.white(`  swarm pipeline run --scope ${opts.output}`));
    });
}
