import { execSync } from 'node:child_process';
import type { PipelineState } from '../types.js';

/**
 * Check if the GitHub CLI (`gh`) is installed and available on PATH.
 */
export function isGhInstalled(): boolean {
  try {
    execSync('which gh', { stdio: 'pipe', encoding: 'utf-8' });
    return true;
  } catch {
    return false;
  }
}

/**
 * Return the current git branch name.
 */
export function getCurrentBranch(): string {
  try {
    return execSync('git rev-parse --abbrev-ref HEAD', { stdio: 'pipe', encoding: 'utf-8' }).trim();
  } catch {
    return 'unknown';
  }
}

/**
 * Return true if the working tree has uncommitted changes (staged or unstaged).
 */
export function hasUncommittedChanges(): boolean {
  try {
    const output = execSync('git status --porcelain', { stdio: 'pipe', encoding: 'utf-8' });
    return output.trim().length > 0;
  } catch {
    return false;
  }
}

/**
 * Build a formatted PR body from pipeline state.
 */
export function buildPRBody(state: PipelineState): string {
  const mayday = state.mayday;
  const featureRequest = mayday?.featureRequest ?? 'N/A';

  // Stage summary
  const stageLines = Object.entries(state.stages).map(([name, stage]) => {
    const icon = stage.status === 'done' ? '✅' : stage.status === 'error' ? '❌' : stage.status === 'skipped' ? '⏭️' : '⏳';
    return `| ${name} | ${icon} ${stage.status} |`;
  });

  // Cost
  const totalCost = state.totalCost.totalUsd.toFixed(4);

  // Agent count
  const agentCount = state.agents.length;

  // Duration
  const startedAt = mayday?.startedAt ?? 0;
  const durationMs = startedAt > 0 ? Date.now() - startedAt : 0;
  const durationMin = (durationMs / 60_000).toFixed(1);

  // Fix iterations
  const fixInfo = mayday
    ? `Fix iterations: ${mayday.fixIteration}/${mayday.maxFixIterations}`
    : '';

  const body = [
    '## Summary',
    '',
    `> ${featureRequest}`,
    '',
    '## Pipeline Stages',
    '',
    '| Stage | Status |',
    '|-------|--------|',
    ...stageLines,
    '',
    '## Metrics',
    '',
    `- **Total cost**: $${totalCost} USD`,
    `- **Agents spawned**: ${agentCount}`,
    `- **Duration**: ${durationMin} min`,
    fixInfo ? `- **${fixInfo}**` : '',
    '',
    '---',
    '_Auto-generated by Swarm MayDay pipeline_',
  ].filter(Boolean).join('\n');

  return body;
}

/**
 * Create a GitHub Pull Request using the `gh` CLI.
 * Returns the PR URL on success.
 */
export function createPR(opts: { title: string; body: string; baseBranch?: string }): string {
  const base = opts.baseBranch ?? 'main';
  try {
    const url = execSync(
      `gh pr create --title "${opts.title.replace(/"/g, '\\"')}" --body "${opts.body.replace(/"/g, '\\"')}" --base ${base}`,
      { stdio: 'pipe', encoding: 'utf-8' },
    );
    return url.trim();
  } catch (err) {
    const message = err instanceof Error ? (err as any).stderr ?? err.message : String(err);
    throw new Error(`Failed to create PR: ${message}`);
  }
}
